export const states = [
    { code: "00", fipsCode: "00", name: "Undefined" },
    { code: "AL", fipsCode: "01", name: "Alabama" },
    { code: "AK", fipsCode: "02", name: "Alaska" },
    { code: "AZ", fipsCode: "04", name: "Arizona" },
    { code: "AR", fipsCode: "05", name: "Arkansas" },
    { code: "CA", fipsCode: "06", name: "California" },
    { code: "CO", fipsCode: "08", name: "Colorado" },
    { code: "CT", fipsCode: "09", name: "Connecticut" },
    { code: "DE", fipsCode: "10", name: "Delaware" },
    { code: "DC", fipsCode: "11", name: "District of Columbia" },
    { code: "FL", fipsCode: "12", name: "Florida" },
    { code: "GA", fipsCode: "13", name: "Georgia" },
    { code: "HI", fipsCode: "15", name: "Hawaii" },
    { code: "ID", fipsCode: "16", name: "Idaho" },
    { code: "IL", fipsCode: "17", name: "Illinois" },
    { code: "IN", fipsCode: "18", name: "Indiana" },
    { code: "IA", fipsCode: "19", name: "Iowa" },
    { code: "KS", fipsCode: "20", name: "Kansas" },
    { code: "KY", fipsCode: "21", name: "Kentucky" },
    { code: "LA", fipsCode: "22", name: "Louisiana" },
    { code: "ME", fipsCode: "23", name: "Maine" },
    { code: "MD", fipsCode: "24", name: "Maryland" },
    { code: "MA", fipsCode: "25", name: "Massachusetts" },
    { code: "MI", fipsCode: "26", name: "Michigan" },
    { code: "MN", fipsCode: "27", name: "Minnesota" },
    { code: "MS", fipsCode: "28", name: "Mississippi" },
    { code: "MO", fipsCode: "29", name: "Missouri" },
    { code: "MT", fipsCode: "30", name: "Montana" },
    { code: "NE", fipsCode: "31", name: "Nebraska" },
    { code: "NV", fipsCode: "32", name: "Nevada" },
    { code: "NH", fipsCode: "33", name: "New Hampshire" },
    { code: "NJ", fipsCode: "34", name: "New Jersey" },
    { code: "NM", fipsCode: "35", name: "New Mexico" },
    { code: "NY", fipsCode: "36", name: "New York" },
    { code: "NC", fipsCode: "37", name: "North Carolina" },
    { code: "ND", fipsCode: "38", name: "North Dakota" },
    { code: "OH", fipsCode: "39", name: "Ohio" },
    { code: "OK", fipsCode: "40", name: "Oklahoma" },
    { code: "OR", fipsCode: "41", name: "Oregon" },
    { code: "PA", fipsCode: "42", name: "Pennsylvania" },
    { code: "RI", fipsCode: "44", name: "Rhode Island" },
    { code: "SC", fipsCode: "45", name: "South Carolina" },
    { code: "SD", fipsCode: "46", name: "South Dakota" },
    { code: "TN", fipsCode: "47", name: "Tennessee" },
    { code: "TX", fipsCode: "48", name: "Texas" },
    { code: "UT", fipsCode: "49", name: "Utah" },
    { code: "VT", fipsCode: "50", name: "Vermont" },
    { code: "VA", fipsCode: "51", name: "Virginia" },
    { code: "WA", fipsCode: "53", name: "Washington" },
    { code: "WV", fipsCode: "54", name: "West Virginia" },
    { code: "WI", fipsCode: "55", name: "Wisconsin" },
    { code: "WY", fipsCode: "56", name: "Wyoming" },
    { code: "PR", fipsCode: "72", name: "Puerto Rico" },
    
];
